import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/IBMPlexSans-Regular.ttf",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/IBMPlexSans-Regular.ttf",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const iBM_Plex_Sans = IBM_Plex_Sans({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700"],
});
console.log(iBM_Plex_Sans);

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
            <link
                href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap"
                rel="stylesheet"
            ></link>
            <body className={`${iBM_Plex_Sans.className}`}>{children}</body>
        </html>
    );
}
